Fix missing method
```
       /tmp/buildpacks/239e234ec277a60eb285d2ac952175495127f09a/lib/language_pack/cache.rb:44:in `exists?': undefined method `exists?' for an instance of Pathname (NoMethodError)
```