Update default Ruby version to 3.3.7 (#1534)
* Update default Ruby version to 3.3.6

The latest Ruby is now 3.4.x. Our ideal default policy is to use the latest release of the prior year's version. This PR updates to the latest Ruby 3.3.x version which is 3.3.6.

* Update to non-deprecated method

* Ruby 3.3.7 is now the default

* Update test apps

* s/exists?/exist?/

Fixes:

```
       -----> Building on the Heroku-24 stack
       -----> Fetching https://github.com/heroku/heroku-buildpack-ruby#schneems/default-ruby-336 buildpack...
              buildpack downloaded
       -----> Ruby app detected
       
        !
        !     undefined method `exists?' for class Dir
        !
       /tmp/buildpacks/55030ecaa578151bf5924184e8750b99212faef5/lib/language_pack/helpers/bundler_wrapper.rb:242:in `fetch_bundler': undefined method `exists?' for class Dir (NoMethodError)
           return true if Dir.exists?(bundler_path)
                             ^^^^^^^^
       Did you mean?  exist?
```

* Update tests

* Bundler default version now 2.3.x

Bundler 1.x is not able to run with Ruby 3.3 in some circumstances:

```
       remote:  !     There was an error parsing your Gemfile, we cannot continue        
       remote:  !     /tmp/d20250127-138-l8vq2r/bundler-1.17.3/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:29:in `root': undefined method `untaint' for an instance of Pathname (NoMethodError)        
       remote:  !             
       remote:  !     Pathname.new(gemfile).untaint.expand_path.parent  
```

This commit updates the default bundler version to 2.3.x.

* Update older rails versions in tests

* Update example to default bundler version

* Update fixtures

* Update fixtures

* Remove unused test

* Remove test

This asserts that we ignore invalid or incorrect patch numbers i.e. p0 in the gem file.lock is not correct:

```
RUBY VERSION
   ruby 2.5.1p0
```

We don't really need to keep and maintain this fixture.

* Fix an error

* Fix spec

* Remove bundler 1.x spec

This no longer builds on the platform:

```
       remote:  !     There was an error parsing your Gemfile, we cannot continue        
       remote:  !     /tmp/d20250204-129-9ld2nw/bundler-1.17.3/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:29:in `root': undefined method `untaint' for an instance of Pathname (NoMethodError)        
       remote:  !             
       remote:  !     Pathname.new(gemfile).untaint.expand_path.parent        
       remote:  !     ^^^^^^^^        
       remote:  !     from /tmp/d20250204-129-9ld2nw/bundler-1.17.3/gems/bundler-1.17.3/lib/bundler.rb:234:in `root'        
       remote:  !     from /tmp/d20250204-129-9ld2nw/bundler-1.17.3/gems/bundler-1.17.3/lib/bundler.rb:246:in `app_config_path'       
```

* Fix fetcher spec and test all bundler versions

* Update fixture

* CI apps that use the database need one

* Fix test

* Fix tests

* Change command so it works on bsdtar (hopefully gnutar tar too, but we will find out one way or another).

* Update tests

* Update fixtures

* Fix missing repo

* Update tests

* Update test

* Update fixture

* Fix test

* Fix test

* Update fixture

* Update fixtures

* Remove-un-needed version write

* Allow heredoc to use interpolation

* Update fixtures

* Fix ruby version

* Update test

* Update fixture

* Update fixtures

* Adjust test addon

* Fix Rails 7 sql/schema test

In Rails 7 the tasks converged into one