Remove bundler 1.x spec
This no longer builds on the platform:

```
       remote:  !     There was an error parsing your Gemfile, we cannot continue        
       remote:  !     /tmp/d20250204-129-9ld2nw/bundler-1.17.3/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:29:in `root': undefined method `untaint' for an instance of Pathname (NoMethodError)        
       remote:  !             
       remote:  !     Pathname.new(gemfile).untaint.expand_path.parent        
       remote:  !     ^^^^^^^^        
       remote:  !     from /tmp/d20250204-129-9ld2nw/bundler-1.17.3/gems/bundler-1.17.3/lib/bundler.rb:234:in `root'        
       remote:  !     from /tmp/d20250204-129-9ld2nw/bundler-1.17.3/gems/bundler-1.17.3/lib/bundler.rb:246:in `app_config_path'       
```